-- CreateTable
CREATE TABLE "SELECT_FILTER" (
    "id" TEXT NOT NULL,
    "labelColumn" TEXT NOT NULL,
    "viewId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SELECT_FILTER_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SELECT_FILTER_viewId_key" ON "SELECT_FILTER"("viewId");

-- AddForeignKey
ALTER TABLE "SELECT_FILTER" ADD CONSTRAINT "SELECT_FILTER_viewId_fkey" FOREIGN KEY ("viewId") REFERENCES "VIEWS"("id") ON DELETE CASCADE ON UPDATE CASCADE;
