-- DropForeignKey
ALTER TABLE "VIEWS" DROP CONSTRAINT "VIEWS_panelId_fkey";

-- AddForeignKey
ALTER TABLE "VIEWS" ADD CONSTRAINT "VIEWS_panelId_fkey" FOREIGN KEY ("panelId") REFERENCES "PANELS"("id") ON DELETE CASCADE ON UPDATE CASCADE;
