export const reactQueryKeys = {
  queries: {
    findPanelQuery: 'findPanelQuery',
    findAllPanelsQuery: 'findAllPanelsQuery',
    findAllDataFontsQuery: 'findAllDataFontsQuery',
    findSchemasQuery: 'findSchemasQuery',
    findTablesQuery: 'findTablesQuery',
    findPanelChartViews: 'findPanelChartViews',
    findUserByToken: 'findUserByToken',
    findAllFavoriteQueriesQuery: 'findAllFavoriteQueriesQuery',
    findAllViews: 'findAllViews',
  },
  mutations: {
    createUserMutation: 'createUserMutation',
    createSessionMutation: 'createSessionMutation',
    createPanelMutation: 'createPanelMutation',
    createDataFontMutation: 'createDataFontMutation',
    deleteDataFontMutation: 'deleteDataFontMutation',
    executeSqlMutation: 'executeSqlMutation',
    deletePanelMutation: 'deletePanelMutation',
    savePanelMutation: 'savePanelMutation',
    saveFavoriteQueryMutation: 'saveFavoriteQueryMutation',
    deleteFavoriteQueryMutation: 'deleteFavoriteQueryMutation',
    updateUserMutation: 'updateUserMutation',
  },
};
