-- CreateTable
CREATE TABLE "NUMBER_VIEW" (
    "id" TEXT NOT NULL,
    "number" DOUBLE PRECISION NOT NULL,
    "subTitle" TEXT,
    "isPercentage" BOOLEAN NOT NULL DEFAULT false,
    "numberOfDecimaPlaces" INTEGER NOT NULL DEFAULT 2,
    "viewId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NUMBER_VIEW_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "NUMBER_VIEW_viewId_key" ON "NUMBER_VIEW"("viewId");

-- AddForeignKey
ALTER TABLE "NUMBER_VIEW" ADD CONSTRAINT "NUMBER_VIEW_viewId_fkey" FOREIGN KEY ("viewId") REFERENCES "VIEWS"("id") ON DELETE CASCADE ON UPDATE CASCADE;
