-- DropForeignKey
ALTER TABLE "PIE_CHART" DROP CONSTRAINT "PIE_CHART_viewId_fkey";

-- DropForeignKey
ALTER TABLE "VIEWS" DROP CONSTRAINT "VIEWS_panelId_fkey";

-- AddForeignKey
ALTER TABLE "VIEWS" ADD CONSTRAINT "VIEWS_panelId_fkey" FOREIGN KEY ("panelId") REFERENCES "PANELS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PIE_CHART" ADD CONSTRAINT "PIE_CHART_viewId_fkey" FOREIGN KEY ("viewId") REFERENCES "VIEWS"("id") ON DELETE CASCADE ON UPDATE CASCADE;
